//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysteryGuest_INC.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ODBC")]
        public string GameDatabase_ConnectionMethod {
            get {
                return ((string)(this["GameDatabase_ConnectionMethod"]));
            }
            set {
                this["GameDatabase_ConnectionMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KN_online")]
        public string GameDatabase_Server {
            get {
                return ((string)(this["GameDatabase_Server"]));
            }
            set {
                this["GameDatabase_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("knight")]
        public string GameDatabase_User {
            get {
                return ((string)(this["GameDatabase_User"]));
            }
            set {
                this["GameDatabase_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("knight")]
        public string GameDatabase_Password {
            get {
                return ((string)(this["GameDatabase_Password"]));
            }
            set {
                this["GameDatabase_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameDatabase_DatabaseName {
            get {
                return ((string)(this["GameDatabase_DatabaseName"]));
            }
            set {
                this["GameDatabase_DatabaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string GameDatabase_TestPassed {
            get {
                return ((string)(this["GameDatabase_TestPassed"]));
            }
            set {
                this["GameDatabase_TestPassed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ODBC")]
        public string AccountDatabase_ConnectionMethod {
            get {
                return ((string)(this["AccountDatabase_ConnectionMethod"]));
            }
            set {
                this["AccountDatabase_ConnectionMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KN_online")]
        public string AccountDatabase_Server {
            get {
                return ((string)(this["AccountDatabase_Server"]));
            }
            set {
                this["AccountDatabase_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("knight")]
        public string AccountDatabase_User {
            get {
                return ((string)(this["AccountDatabase_User"]));
            }
            set {
                this["AccountDatabase_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("knight")]
        public string AccountDatabase_Password {
            get {
                return ((string)(this["AccountDatabase_Password"]));
            }
            set {
                this["AccountDatabase_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AccountDatabase_DatabaseName {
            get {
                return ((string)(this["AccountDatabase_DatabaseName"]));
            }
            set {
                this["AccountDatabase_DatabaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string AccountDatabase_TestPassed {
            get {
                return ((string)(this["AccountDatabase_TestPassed"]));
            }
            set {
                this["AccountDatabase_TestPassed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string SaveDatabaseSettings {
            get {
                return ((string)(this["SaveDatabaseSettings"]));
            }
            set {
                this["SaveDatabaseSettings"] = value;
            }
        }
    }
}
